### ISSUE TITLE
Can't open newly-added field inlines in admin (Firefox 9)

### ISSUE THREAD

**Issue by ringemup** [samluescher/django-form-designer#34]
Using FF 9.0.1 on Mac;  Django-CMS not installed.  I cllick "add another field".  The fieldset ("Field: (Show) #2") appears at the bottom of the form, but it's collapsed.  Clicking the "show" link does nothing.  After "save and continue editing" it can be uncollapsed.

**Comment by samluescher** [comment]
Fixed in current master, please test.

**Comment by ringemup** [comment]
Still not working with current master on pristine Django instance.  No JS errors on either page load or clicking on the "show" link, but there is a warning on page load:

Warning: Use of getAttributeNodeNS() is deprecated. Use getAttributeNS() instead.
Source File: http://localhost:8000/admin/form_designer/formdefinition/add/
Line: 0

**Comment by samluescher** [comment]
What Django version are you using?

**Comment by ringemup** [comment]
1.2  Is that the problem?

**Comment by samluescher** [comment]
Can you try with 1.3?

**Comment by ringemup** [comment]
It's not working on 1.3.1 either.

**Comment by samluescher** [comment]
I just tested this with Firefox 9.0.1 and can't confirm or reproduce this error. You might be using old JS code (delete and run collectstatic)? 
Keeping this closed for now unless other people experience the same.
